### ISSUE TITLE
Graphics Not Working

### ISSUE THREAD

**Issue by Sierra1231** [UTRGV-SMSS/Thesis-Template#12]
I downloaded the template but when I tried to include images into my file. It did not let me. a white box appeared with the name of the picture but the actual image did not appear. I tried different formats and it still did not work. Even the picture example that came with the template did not load as an image just the white box. 
<img width="316" alt="Screen Shot 2020-07-01 at 9 07 54 PM" src="https://user-images.githubusercontent.com/67720456/86308485-fbcef680-bbde-11ea-8386-61c5c621e9cb.png">

**Comment by ggarza** [comment]
You need to change the `\documentclass` options from `draft` to `final`.

**Comment by Sierra1231** [comment]
Thank you! It worked!
