### ISSUE TITLE
title page changes

### ISSUE THREAD

**Issue by andrasbalogh** [UTRGV-SMSS/Thesis-Template#19]
The following changes were needed based on the Fall 2021 formatting guide https://www.utrgv.edu/graduate/_files/documents/thesis-formatting-guide-september-2021.pdf page 19

1. "Fulfillment" part should be double spaced and should read 
    Submitted in Partial Fulfillment of the 
    Requirements for the Degree of 
    MASTER OF SCIENCE
2. 4 lines of space below: Major Subject: Mathematics
3. 7 lines of space below: 
    The University of Texas Rio Grande Valley 
     May 2022

**Comment by ggarza** [comment]
ok. I think fixed it.  The latest commit should be fine

**Comment by andrasbalogh** [comment]
Thanks!
