### ISSUE TITLE
Font should be Times New Roman

### ISSUE THREAD

**Issue by moemyself3** [UTRGV-SMSS/Thesis-Template#2]
The current manual (Updated June 2018) specifies the font should be Times New Roman.

In an attempt to correct this I used the `fontspec` package, `\setmainfont{Times New Roman}` and used `XeLaTeX` for compiling as required by `fontspec`.

There is still an issue that I haven't looked too deep into; the math font is not Times New Roman.

A good comparison is the following:
Figure 2. The subtle differences in design details are circled in Linotype’s Times Roman in the top example and Monotype’s Times New Roman, below it.
![](https://3v6x691yvn532gp2411ezrib-wpengine.netdna-ssl.com/wp-content/uploads/sites/default/files/story_images/20091015TT_fg02.gif)

[Source: [https://creativepro.com/typetalk-times-roman-vs-times-new-roman/](https://creativepro.com/typetalk-times-roman-vs-times-new-roman/) ]

**Comment by ggarza** [comment]
We are aware of that particular requirement.  I believe it's always been there.

It's great that you found a workaround.  We usually just ask the proofreaders to accept the thesis the way it is.

I would say that it doesn't matter that the math font is not the same as your main font. I doubt anybody would notice while reading your thesis. 

It's difficult to get the text font and the math font to be the same.  In LaTeX, the fonts are designed and tuned to be used for math mode.  But if you want to try anyway, here's a start:
https://tex.stackexchange.com/questions/96024/how-to-use-system-font-for-equation-in-xelatex

I suggest you create and submit a pull request for compiling with XeLaTeX.  However, I would prefer that the template still compile under LaTeX with the previous font choice.  Maybe something similar to the following (with the appropriate fonts):
https://github.com/Tufte-LaTeX/tufte-latex/blob/d7017ab102387c2f24bc608e073bfc8da2de16ad/tufte-common.def#L263

**Comment by ggarza** [comment]
For detecting whether compilation is with XeTeX:
https://ctan.org/pkg/ifxetex

**Comment by moemyself3** [comment]
Ah thanks. I have yet to submit, but helped a fellow student with this issue. His work after reviewal had the font listed as a needed change.

I too would like for the template to compile under LaTeX.  I'll see about making the pull request. From what I've seen it seems that XeLaTeX is a workaround commonly used for fonts.

I think once I make the pull request and if you accept the changes, then maybe this issue can be closed with those changes.
