### ISSUE TITLE
committee page formatting

### ISSUE THREAD

**Issue by andrasbalogh** [UTRGV-SMSS/Thesis-Template#20]
The following changes are needed based on the Fall 2021 formatting guide https://www.utrgv.edu/graduate/_files/documents/thesis-formatting-guide-september-2021.pdf page 21

COMMITTEE page: Allow only 1 space between the last line of the THESIS TITLE and “A Thesis” line

**Comment by ggarza** [comment]
Fixed it.  I hope it's the right size space.

**Comment by andrasbalogh** [comment]
Thanks!

From: Guillermo Garza ***@***.***>
Date: Wednesday, March 23, 2022 at 5:27 PM
To: UTRGV-SMSS/Thesis-Template ***@***.***>
Cc: Andras Balogh ***@***.***>, Author ***@***.***>
Subject: Re: [UTRGV-SMSS/Thesis-Template] committee page formatting (Issue #20)

Fixed it. I hope it's the right size space.

**Comment by andrasbalogh** [comment]
Thanks!
