### ISSUE TITLE
sample figure and table should be aligned left

### ISSUE THREAD

**Issue by andrasbalogh** [UTRGV-SMSS/Thesis-Template#21]
In the introduction.tex file the sample figure and table should be left aligned based on the Fall 2021 formatting guide https://www.utrgv.edu/graduate/_files/documents/thesis-formatting-guide-september-2021.pdf page 15
In addition to removing centering, the caption should also be left aligned. Suggestion: \usepackage{caption} 
\captionsetup{slc=off}

**Comment by ggarza** [comment]
Ok. Fixed it in the latest commit.  Thank you.
