### ISSUE TITLE
Few changes to the UTRGV Thesis template

### ISSUE THREAD

**Issue by RaghavGirgaonkar** [UTRGV-SMSS/Thesis-Template#29]
Hi,
I am submitting my Masters thesis by the end of Spring 2024. I recently received some comments on my preliminary draft that required me to make some changes to the .cls file. Some of these are:

1. No need for "Table of Contents" entry in the Table of Contents. Currently it is displayed as an entry.
2. Chapter names in the TOC should be listed as " CHAPTER <name>: " instead of the current "CHAPTER <name>. " (replacing a period with a colon)
3. If one has multiple Appendices, each appendix was being listed in the TOC, instead the ETD requires that there be only one entry called "APPENDIX" or "APPENDICES" in the TOC at the beginning of all the appendices. 
4. Following up on point 3. currently, the number of appendices are also listed in the Abstract page along with the number of pages, figures and tables, this is no longer needed. 
5. The Biographical Sketch section is now named VITA. 

Most of the above points are minor but important for the overall format. To address these I went into the .cls file and I made the changes. If possible, we could include this updated version of cls files for future reference, along with a list of what changes were made. I'd be happy to share my updated cls file. 

Additionally, it is also required that in the List of Figures and List of Tables, that only the first sentence of your Table/Figure caption be printed. While this doesn't require any changes to the cls file, if it's okay, a small note can be added on how to do this for future template users. 

These files and notes could be updated regularly or as need. 

Thanks.

**Comment by ggarza** [comment]
Thanks for writing this up.  

If possible, please submit the updated cls file you created as part of a pull request.  You could also try updating the README with the requirement for the list of Figures and Tables

I really appreciate this.

**Comment by RaghavGirgaonkar** [comment]
Great! Thanks! I will submit a pull request.
