### ISSUE TITLE
Fig doesn't show up

### ISSUE THREAD

**Issue by QYQSDTC** [UTRGV-SMSS/Thesis-Template#5]
![image](https://user-images.githubusercontent.com/15608306/60307397-0ee32280-990a-11e9-9bcc-efb269e44aa4.png)
Compiled by pdfLatex and the figure doesn't show up.

**Comment by ggarza** [comment]
You have change the `\documentclass` options from `draft` to `final`.

The `draft` option is used when editing your paper to speed up compilation and maybe save your ink.
