### ISSUE TITLE
Generating blank pages, not always needed

### ISSUE THREAD

**Issue by moemyself3** [UTRGV-SMSS/Thesis-Template#7]
According to the thesis guide:
>Blank Page (no page number) (needed only if the total number of
>pages for the table of contents is an odd number)

It seems that it's assumes to always need a blank page.

https://github.com/UTRGV-SMSS/Thesis-Template/blob/5ae9659879a13d4d984d9ad165b342603fc2d1df/UTRGVthesis.cls#L341-L355

**Comment by moemyself3** [comment]
I'm not sure if there is a way to count the number of pages generated, then make a decision.
It seems tricky since this is dependent on content.

**Comment by ggarza** [comment]
Thanks for informing me.  I've been meaning to fix this.  

The`\ifodd` macro seems useful.

https://en.wikibooks.org/wiki/TeX/ifodd
